<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Token' => '',
    'Anexo' => '',
    'Are you sure you want to delete this item?' => 'Realmente você deseja exluir este item?',
    'Auth Key' => '',
    'Biometria' => '',
    'Browser here' => 'Menu',
    'Cod Material' => 'Cod. Material',
    'Continue save' => 'Continuar salvando',
    'Create Event' => 'Cadastrar Escala',
    'Create Funcionario' => 'Cadastrar Funcionario',
    'Create Funcionario Has Material' => 'Cadastrar Equipamento em Estoque',
    'Create Horario Extra' => 'Cadastrar Hora Extra',
    'Create Justificativa' => 'Cadastrar Justificativa',
    'Create Material' => 'Cadastrar Equipamento',
    'Create Ponto' => '',
    'Create Usuario' => 'Cadastrar Usuário',
    'Dashboard' => 'Início',
    'Data Dev' => 'Data de Devolução',
    'Data Emp' => 'Data de Emprestimo',
    'Delete' => 'Excluir',
    'Description' => 'Setor',
    'Employees' => 'Funcionário',
    'End' => '',
    'Ending' => 'Emprestimos',
    'Event ID' => '',
    'Events' => 'Escala',
    'Finish' => '',
    'Funcionario Has Materials' => 'Controle de Equipamento',
    'Funcionario Id Funcionario' => 'Nome Funcionário',
    'Funcionarios' => '',
    'Generate report scale' => 'Gerar relatório de escala',
    'Hash Biometria' => '',
    'Hora Chegada' => '',
    'Hora Saida' => '',
    'Horario Extras' => '',
    'Horas Excedidas' => '',
    'ID' => '',
    'Id Funcionario' => 'Cod. Funcionario',
    'Id Funcionario Has Material' => 'Cod. Estoque',
    'Id Horario Extra' => '',
    'Id Justificativa' => '',
    'Id Material' => 'Cod. Equipamento',
    'Id Ponto' => '',
    'Id Usuario' => 'Cod. Usuário',
    'Justificativas' => '',
    'Material Id Material' => 'Nome Equipamento',
    'Materials' => '',
    'Matricula' => '',
    'Motivo' => '',
    'Nome' => '',
    'Nome Material' => '',
    'Password' => 'Senha',
    'Pontos' => '',
    'Qtd Dev' => 'Quant. Devolvida',
    'Qtd Posse' => 'Quant. Emprestada',
    'Quant' => 'Quantidade em estoque',
    'Register' => 'Cadastrar',
    'Register loan' => 'Cadastrar Emprestimo',
    'Report' => 'Relatórios',
    'Reset' => '',
    'Save' => 'Salvar',
    'Scale' => 'Escala',
    'Search' => '',
    'Select an employee' => 'Selecione um funcionário',
    'Select the material to borrow' => 'Selecione um equipamento a ser emprestado',
    'Start' => '',
    'Status' => 'STATUS',
    'Stock' => 'Estoque',
    'The requested page does not exist.' => 'A página requisitada não existe.',
    'Title' => 'Nome do Funcionario',
    'Type' => 'Tipo',
    'Update' => 'Atualizar',
    'Update Event: {name}' => '',
    'Update Funcionario Has Material: {name}' => '',
    'Update Funcionario: {name}' => 'Atualizar Funcionário',
    'Update Horario Extra: {name}' => '',
    'Update Justificativa: {name}' => '',
    'Update Material: {name}' => '',
    'Update Ponto: {name}' => '',
    'Update Usuario: {name}' => 'Atualizar Usuário',
    'Username' => '',
    'Usuario Id Usuario' => 'ID Usuário',
    'Usuarios' => '',
    'View loan' => 'Visualizar emprestimos',
];
