<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Anexo' => '',
    'Are you sure you want to delete this item?' => '',
    'Biometria' => '',
    'Cargo' => '',
    'Create Escala' => '',
    'Create Funcionario' => '',
    'Create Horario Extra' => '',
    'Create Justificativa' => '',
    'Create Ponto' => '',
    'Create Usuario' => '',
    'Data Escalado' => '',
    'Data Escalar' => '',
    'Data Faltiva' => '',
    'Delete' => '',
    'Escala Id Escala' => '',
    'Escalas' => '',
    'Funcionario Id Funcionario' => '',
    'Funcionarios' => '',
    'Hora Chegada' => '',
    'Hora Inicio' => '',
    'Hora Saida' => '',
    'Hora Termino' => '',
    'Horario Extras' => '',
    'Horas Excedidas' => '',
    'Id Escala' => '',
    'Id Funcionario' => '',
    'Id Horario Extra' => '',
    'Id Justificativa' => '',
    'Id Ponto' => '',
    'Id Usuario' => '',
    'Justificativas' => '',
    'Local' => '',
    'Login' => '',
    'Matricula' => '',
    'Motivo' => '',
    'Nome' => '',
    'Password' => '',
    'Ponto Id Ponto' => '',
    'Pontos' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Status' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update Escala: {name}' => '',
    'Update Funcionario: {name}' => '',
    'Update Horario Extra: {name}' => '',
    'Update Justificativa: {name}' => '',
    'Update Ponto: {name}' => '',
    'Update Usuario: {name}' => '',
    'Usuario Id Usuario' => '',
    'Usuarios' => '',
];
